### ISSUE TITLE
XML Feed is not parsed

### ISSUE THREAD

**Issue by clemsos** [christopheradams/christopheradams.github.io#1]
Cool website ! Just found out that  https://christopheradams.io/feed.xml

**Comment by christopheradams** [comment]
can you say more?

**Comment by clemsos** [comment]
Yes, sorry :) I think the feed is served properly but there is no XML parser so you end up with a markdown feed, which is not valid XML (see the pic).
 
![selection_205](https://cloud.githubusercontent.com/assets/743246/21814158/ab2ddcd2-d758-11e6-9c16-f64d243f912d.png)


Adding this file to the main rep will give you a valid XML for syndication https://github.com/clemsos/clemsos.github.io/blob/master/feed.xml

**Comment by christopheradams** [comment]
The feed is generated automatically by the `jekyll-feed` gem. It adds a stylesheet https://christopheradams.io/feed.xslt.xml which makes the feed look that way (at least in Chrome). The XML is valid.

**Comment by clemsos** [comment]
arf ! sorry for the noise :) I didn't know about any XLST parsing in the browser... thought it was supposed to display plain XML and it was Mardown. Anyway, cool wesbite ! cheers

**Comment by christopheradams** [comment]
Thanks!
